FROM node:alpine

RUN mkdir /project
WORKDIR /project

RUN npm install -g @angular/cli@13

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
CMD if [ "$ENV" = "production" ]; then \
    ng serve --configuration=production --host 0.0.0.0; \
else \
    ng serve --host 0.0.0.0; \
fi